language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install .
script: py.test tests
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: lIE5UJbhbV7J6N3xOSWxl75rEpJC40iwhMSKsKYzkC/HvgDmUbG++uBc4RPsPRwi4GMcbZFHG8s+0e1RDW52Hw6z1tvKsmC/V4AEDcT9imR3F9cWpihyu16oIu8c4GVyjS6hGullJjwyhtnjNGDxMtjzhi4MHYz6loYqZMa9TEP2viQ1KM1cpC4YKkzKTd+1Lc5fdKDnYLEGJw/CEH6SaWd7wevRpk77xWhodl0hDsvrQWdgWtSMadz787E2pniOaNW2ZAsjqV09i31u+tuoVMOvo4q7MdSetwSWW+VnETFTyeg+wv0FlRMhJc/oTxfAaO4vqqCJoxKwAzFpbsFRNjp1y5wQfnLHSgBWWpjKKe8svl0oaP5wP1Norbe7H2+FBxTuKc6MDRaO2V1q0V3njVXTCQk8RuLZkE3ln6rlGMZ9B8KidKY2YJF4p2uiiKxM8VhNCP1W4NZ1HiqvF9N5WpLiz/He/Zz84U5A2VfYLrrmu3T6X5xfKpmU9Uaxi7WSqye6z+inzbU3yX17jjE/V72yU+sjxVAVNfckO3c44sbDCqxkmcC9dTTB4ARTWUiEeSA1qajrKLsIdwwOIhMMbmMZntFugwau9UMV46Ol9cJfaenAt0SzZx5EbM5iVk4yaIrDMaw0ZsxzO1icmFYq8FhOZMBXU89XySSyjyvmP6A=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/pythonwhat-ext
  skip_upload_docs: true
